sudo: false
cache: yarn
language: node_js
node_js:
  - "stable"
addons:
  sauce_connect: true
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
